=== gestione_inventario ===
TODO: trasformare in funzione
+ {doniTrovati == banana} Doni una banana
    ~ doniTrovati -= banana
    ~ doniDonati += banana
    ->->
        TODO: prima di tornare da dove vengo, devo attribuire una frase allo spettro con cui sto parlando e un relativo valore di inchiostro.
+ {doniTrovati == mela} Doni una mela
    ~ doniTrovati -= mela
    ~ doniDonati += mela
    ->->
+ Mmm, per ora passo ->->   
+ ->
-
-> DONE